# data2vec_optimized_245.yaml
# @package _group_

common:
  fp16: true
  log_format: json
  log_interval: 100
  tensorboard_logdir: tb
  user_dir: /mnt5/noy/SpectralFM/fairseq/examples/data2vec
  wandb_project: "spectralfm_batch_sweep"
  wandb_run_name: "5m_data_bs32_uf2"
    #wandb_run_name:  lr${optimizer.lr[0]}_mtok${dataset.max_tokens}_mp${model.mask_prob}_ml${model.mask_length}_${task.data}  

checkpoint:
  save_interval: 1
  save_interval_updates: 500 # fixme change to 1k 
  keep_interval_updates: 3
  no_epoch_checkpoints: true

task:
  _name: audio_pretraining
  data: /mnt5/noy/fairseq/data/single_channel_all/
  # Adjusted to safely include your file length of 245
  max_sample_size: 500  
  min_sample_size: 200
  normalize: true # Kept from base config; set to false if your data is pre-normalized

    # hydra:
    #   job:
    #     env_set:
    #       WANDB_PROJECT: train_feature_extractor_optimized
    #       wandb_run_name: data2vec_245_len_optimized
    #         # wandb_run_name:  lr${optimizer.lr[0]}_mtok${dataset.max_tokens}_mp${model.mask_prob}_ml${model.mask_length}_${task.data}

dataset:
  num_workers: 4
  # FIXED OOM: Replaced max_tokens with max_sentences (batch size)
  # Start with 128. If you have memory left, try 256 or 512.
  # max_sentences: 128
  batch_size: 320
  validate_interval_updates: 500 # fixme change to 1k or more  
  skip_invalid_size_inputs_valid_test: true
  validate_interval: 1
  valid_subset:  valid
  required_batch_size_multiple: 1
  disable_validation: false


distributed_training:
  distributed_world_size: 8
  ddp_backend: legacy_ddp

criterion:
  _name: model
  log_keys:
    - ema_decay
    - target_var
    - pred_var

optimization:
  max_update: 21000
  max_epoch: 22  
  lr: [0.001]
  update_freq: [4]
  # Optional: Increase update_freq to simulate larger batches if needed
  # update_freq: [1] 

optimizer:
  _name: adam
  adam_betas: (0.9,0.98)
  adam_eps: 1e-06
  weight_decay: 0.01

lr_scheduler: 
  #_name: fixed
  _name: tri_stage # fixme removed for now
  phase_ratio: [0.1, 0.4, 0.5]

model:
  _name: data2vec_audio
  extractor_mode: layer_norm
  encoder_layerdrop: 0.05
  dropout_input: 0.0
  dropout_features: 0.0
  feature_grad_mult: 1.0
  encoder_embed_dim: 768
  
  conv_feature_layers: '[(512, 3, 1), (512, 3, 1), (512, 3, 1), (512, 3, 1), (512, 5, 5)]'
  mask_prob: 0.4
  mask_length: 10

  loss_beta: 0
  loss_scale: null

  instance_norm_target_layer: true
  average_top_k_layers: 8

  pos_conv_depth: 5
  conv_pos: 95

  ema_decay: 0.999
  ema_end_decay: 0.9999
  ema_anneal_end_step: 30000
  ema_transformer_only: true
  ema_layers_only: true

  require_same_masks: true
  mask_dropout: 0
